version: "3"

services:
  db_dev:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: ./backend/
    command: bash -c "make run"
    volumes:
      - ./backend:/code
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db_dev
      - localstack

  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:8080"
    depends_on:
      - db_dev

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
    volumes:
      - './docker/localstack:/docker-entrypoint-initaws.d'
